### PR TITLE
Follow `open` state in controlled mode

### LINKED ISSUE #53: Floater does not always go away in controlled mode
## 🐛 Bug Report

If you thrash the state of the floater in controlled mode, it sometimes does not go away even though `open={false}`

## To Reproduce

Quickly move your mouse over the "Hover Me" button. You should eventually get a floater with the text "I should not be open"

## Expected behavior

The floater should disappear when `open={false}` in controlled mode

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/pwwppv1060?fontsize=14

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash

npx: installed 1 in 1.991s

  System:
    OS: Linux 5.0 Fedora 29 (Workstation Edition) 29 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 4.92 GB / 31.15 GB
    Container: Yes
    Shell: 4.4.23 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.13.0 - /home/linuxbrew/.linuxbrew/bin/yarn
    npm: 6.8.0 - ~/Projects/vimily/bonjoro/node_modules/.bin/npm
  npmPackages:
    react-floater: ^0.6.4 => 0.6.4 

```

### PR DESCRIPTION
**Pull request by deevus**
- Fixes #53 

https://codesandbox.io/s/py400w9o5q

Side note:
I couldn't get the tests to pass in my development environment and I didn't see any notes on how to configure it in the README.

### CODE REVIEW

**Comment by gilbarbara** [comment]
hey,

How to configure the tests? I'm not sure I understand what you meant.

**Comment by deevus** [comment]
Nevermind. I installed packages using `yarn` out of habit. Once I nuked `node_modules` and installed using `npm install` the tests worked fine.

**Comment by deevus** [comment]
Apparently I didn't save the codesandbox changes. Sorry about that.

**Comment by deevus** [comment]
@gilbarbara What do you need from me to merge this?

**Comment by gilbarbara** [comment]
@deevus Patience :)

**Comment by deevus** [comment]
Just making sure you haven't forgotten about this.

**Pull request merged**
