### PR TITLE
Include react ^17.0.0 in the peer dependencies

### PR DESCRIPTION
**Pull request by molp**

### CODE REVIEW

**Comment by blakmatrix** [comment]
Would be nice to get this merged ( using react-joyride and getting dependency errors between react and this module)

**Comment by codyduval** [comment]
Anything we can do to get this merged? Also using `react-joyride` and this is blocking a clean upgrade to react 17 for us. Thank you!

**Comment by romanlex** [comment]
bus factor?

**Review by gilbarbara — APPROVED** [review]
LGTM

**Pull request merged**
